name: Larastan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon'
      - 'composer.json'

jobs:
  larastan:
    name: larastan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v1

      - name: Run Larastan
        run: ./vendor/bin/phpstan --error-format=github
